#pragma config(Motor,  port1,           left_back,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           right_front,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right_back,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           left_front,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           right_arm_lower, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           right_arm_upper, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left_arm_upper, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          left_arm_lower, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	for(;;)
	{
		motor[right_front] = vexRT[Ch1] + vexRT[Ch4] - vexRT[Ch2];
		motor[left_front] =  vexRT[Ch1] + vexRT[Ch4] + vexRT[Ch2];
		motor[left_back] = vexRT[Ch1] - vexRT[Ch4] + vexRT[Ch2];
		motor[right_back] =  vexRT[Ch1] - vexRT[Ch4] - vexRT[Ch2];

		motor[left_arm_lower] = vexRT[Ch3];
	  motor[left_arm_upper] = vexRT[Ch3];
		motor[right_arm_lower] = vexRT[Ch3];
		motor[right_arm_upper] = vexRT[Ch3];
	}
}
